project:
  type: website
  output-dir: _site

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "kikkupico"
  search: false
  navbar:
    right:
      - icon: question-circle
        text: " "
        href: about.qmd
        aria-label: About
      - icon: file-text
        text: " "
        href: resume.qmd
        aria-label: Resume
      - icon: github
        href: https://github.com/kikkupico
      - icon: linkedin
        href: https://www.linkedin.com/in/ramakrishnan-veeraragavan-725797205/
format:
  html:
    theme:
      - cosmo
      - custom.scss



